apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: data-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: data-repo-api
  template:
    metadata:
      labels:
        app: data-repo
        component: data-repo-api
    spec:
      serviceAccountName: jade-sa
      initContainers:
      - name: check-db-ready
        image: postgres:9.6.5
        command: ['sh', '-c','until pg_isready -h postgres-service.data-repo -p 5432;do echo waiting for database; sleep 2; done;']
      volumes:
      - name: google-cloud-key
        secret:
          secretName: sa-key
      containers:
      - name: data-repo-api-container
        image: gcr.io/broad-jade-dev/jade-data-repo:latest
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        ports:
        - containerPort: 8080
        - containerPort: 5005
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/sa-key.json
        - name: OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: oauth-client-id
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: google-cloud-project
        - name: DB_DATAREPO_URI
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: datarepo-uri
        - name: DB_DATAREPO_USERNAME
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: datarepo-username
        - name: DB_DATAREPO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: datarepo-password
        - name: DB_STAIRWAY_URI
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: stairway-uri
        - name: DB_STAIRWAY_USERNAME
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: stairway-username
        - name: DB_STAIRWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: stairway-password
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: spring-profiles-active
