apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: data-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: data-repo-api
  template:
    metadata:
      labels:
        app: data-repo
        component: data-repo-api
    spec:
      serviceAccountName: jade-sa
      initContainers:
      - name: check-db-ready
        image: postgres:9.6.5
        env:
          - name: DB_DATAREPO_USERNAME
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: datarepo-username
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: datarepo-password
        command: ["/bin/sh" , "-c", "psql -h cloudsql-proxy-service.data-repo -U drmanager -d datarepo -c \"CREATE EXTENSION IF NOT EXISTS pgcrypto;\""]
      volumes:
      - name: google-cloud-key
        secret:
          secretName: sa-key
      containers:
      - name: data-repo-api-container
        image: gcr.io/broad-jade-dev/jade-data-repo:latest
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        ports:
        - containerPort: 8080
        - containerPort: 5005
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/sa-key.json
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: google-cloud-project
        - name: DB_DATAREPO_USERNAME
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: datarepo-username
        - name: DB_DATAREPO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: datarepo-password
        - name: DB_STAIRWAY_USERNAME
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: stairway-username
        - name: DB_STAIRWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: stairway-password
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: spring-profiles-active
