before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/google-cloud-sdk/

env:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1

language: java

jdk:
  - oraclejdk8
  - openjdk8

addons:
  postgresql: "9.6"

services:
  - docker
  - postgresql

before_install:
  - if [ ! -d ${HOME}/google-cloud-sdk/bin ]; then
      rm -rf $HOME/google-cloud-sdk;
      curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - ls -la $HOME/google-cloud-sdk
  - which gcloud
  - gcloud config set project $INTEGRATION_PROJECT
  - gcloud config set compute/zone $INTEGRATION_ZONE
  - echo "${SA_JSON}" > $GOOGLE_APPLICATION_CREDENTIALS
  - gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
  - gcloud components install kubectl
  - gcloud container clusters get-credentials $CLUSTER_NAME

before_script:
  - psql -U postgres -f db/create-data-repo-db

script:
  - ./gradlew assemble
  - ./gradlew check
  - ./gradlew dockerPush

# deploy:
#   provider: script
#   script: # deploy to dev
#   on:
#     branch: develop
