apiVersion: skaffold/v2alpha2
kind: Config
build:
  artifacts:
  - image: gcr.io/broad-jade-dev/jade-data-repo
    jib:
      args:
      - jib
      type: gradle
deploy:
  kubectl:
    manifests:
    - https://raw.githubusercontent.com/broadinstitute/datarepo-helm-definitions/master/dev/ms/msHelmOperator.yaml
