apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: gcr.io/broad-jade-dev/jade-data-repo
    jibGradle:
      args:
      - jib
deploy:
  kubectl:
    manifests:
    - ops/k8s/deployments/api-deployment.yaml
    flags:
      global:
        - --namespace=data-repo

