name: 'configure-credentials'
run: |
  # write vault tokens
  base64 --decode <<< ${B64_APPLICATION_CREDENTIALS} > ${GOOGLE_APPLICATION_CREDENTIALS}
  jq -r .private_key ${GOOGLE_APPLICATION_CREDENTIALS} > ${GOOGLE_SA_CERT}

  gcloud auth activate-service-account --key-file ${GOOGLE_APPLICATION_CREDENTIALS}

  # configure integration prerequisites
  gcloud config set compute/zone ${GOOGLE_ZONE} --quiet
  gcloud config set project ${GOOGLE_CLOUD_PROJECT} --quiet
  gcloud auth configure-docker --quiet
  #echo 'Set google sdk to SA user'
  if [[ -n "${K8_CLUSTER}" ]]; then
    gcloud container clusters get-credentials ${K8_CLUSTER} --zone ${GOOGLE_ZONE}
  fi
