kind: Service
apiVersion: v1
metadata:
  name: oidc-proxy-service
spec:
  selector:
    component: data-repo-oidc-proxy
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  - protocol: TCP
    name: https
    port: 443
    targetPort: 443
