kind: Service
apiVersion: v1
metadata:
  namespace: data-repo
  name: oidc-proxy-service
spec:
  type: LoadBalancer
  selector:
    component: data-repo-oidc-proxy
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  - protocol: TCP
    name: https
    port: 443
    targetPort: 443
