databaseChangeLog:
  - changeSet:
      id: add_snapshot_id_to_settings
      author: rjohanek
      changes:
        - addColumn:
            tableName: snapshot_builder_settings
            columns:
              - column:
                  name: snapshot_id
                  type: ${uuid_type}
                  constraints:
                    unique: true
                    foreignKeyName: fk_snapshot_snapshot_builder_settings
                    references: snapshot(id)
                    deleteCascade: true
        - dropNotNullConstraint:
            tableName: snapshot_builder_settings
            columnName: dataset_id
