/*
 * Rawls
 * Rawls API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package bio.terra.app.model.rawls;

import bio.terra.app.utils.PolicyUtils;
import bio.terra.model.ResourcePolicyModel;
import bio.terra.model.WorkspacePolicyModel;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * WorkspaceResponse
 *
 * <p>This class was generated by swagger-codegen from the Rawls API spec, but then augmented to fit
 * our needs
 */
public class WorkspaceResponse {

  @SerializedName("workspace")
  private WorkspaceDetails workspace = null;

  public WorkspaceResponse workspace(WorkspaceDetails workspace) {
    this.workspace = workspace;
    return this;
  }

  /**
   * Get workspace
   *
   * @return workspace
   */
  @Schema(description = "")
  public WorkspaceDetails getWorkspace() {
    return workspace;
  }

  public void setWorkspace(WorkspaceDetails workspace) {
    this.workspace = workspace;
  }

  public WorkspacePolicyModel toWorkspacePolicyModel(
      List<ResourcePolicyModel> resourcePolicyModels, String terraBasePath) {
    return new WorkspacePolicyModel()
        .workspaceId(UUID.fromString(workspace.getWorkspaceId()))
        .workspaceName(workspace.getName())
        .workspaceNamespace(workspace.getNamespace())
        .workspacePolicies(PolicyUtils.resourcePolicyToPolicyModel(resourcePolicyModels))
        .workspaceLink(
            String.format(
                "%s/#workspaces/%s/%s",
                terraBasePath, workspace.getNamespace(), workspace.getName()));
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkspaceResponse workspaceResponse = (WorkspaceResponse) o;
    return Objects.equals(this.workspace, workspaceResponse.workspace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workspace);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkspaceResponse {\n");
    sb.append("    workspace: ").append(toIndentedString(workspace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
