apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: data-repo
    component: data-repo-db
spec:
  hostname: postgres
  containers:
    - name: postgres
      image: postgres:9.6
      imagePullPolicy: "IfNotPresent"
      ports:
        - containerPort: 5432
