kind: Service
apiVersion: v1
metadata:
  name: oidc-proxy-service
spec:
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  type: NodePort
  selector:
    service: oidc
    project: datarepo
