package bio.terra.validation;

import bio.terra.model.AssetModel;
import bio.terra.model.AssetTableModel;
import bio.terra.model.ColumnModel;
import bio.terra.model.RelationshipModel;
import bio.terra.model.RelationshipTermModel;
import bio.terra.model.StudyRequestModel;
import bio.terra.model.StudySpecificationModel;
import bio.terra.model.TableModel;
import org.springframework.stereotype.Component;
import org.springframework.validation.Errors;
import org.springframework.validation.Validator;

import javax.validation.constraints.NotNull;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;

import static java.util.stream.Collectors.toList;

/**
 * This validator runs along with the constraint validation that comes from the Models generated by swagger-codegen.
 * The constraints will be able to handle things like nulls, but not things like uniqueness or other structural
 * validations.
 *
 * There are a lot of null checks here because this will still be called even if a constraint validation failed.
 * Spring will not shortcut out early if a validation fails, so this Validator will still get nulls and should only
 * validate if the field is present.
 */
@Component
public class StudyRequestValidator implements Validator {

    @Override
    public boolean supports(Class<?> clazz) {
        return true;
    }

    private static class SchemaValidationContext {

        private HashMap<String, HashSet<String>> tableColumnMap;
        private HashSet<String> relationshipNameSet;

        SchemaValidationContext() {
            tableColumnMap = new HashMap<>();
            relationshipNameSet = new HashSet<>();
        }

        void addTable(String tableName, List<String> columnNames) {
            tableColumnMap.put(tableName, new HashSet<>(columnNames));
        }

        void addRelationship(String relationshipName) {
            relationshipNameSet.add(relationshipName);
        }

        boolean isValidTable(String tableName) {
            return tableColumnMap.containsKey(tableName);
        }

        boolean isValidTableColumn(String tableName, String columnName) {
            return isValidTable(tableName) && tableColumnMap.get(tableName).contains(columnName);
        }

        boolean isValidRelationship(String relationshipName) {
            return relationshipNameSet.contains(relationshipName);
        }
    }

    private void validateStudyName(String studyName, Errors errors) {
        if (studyName == null) {
            errors.rejectValue("name", "StudyNameMissing");
        } else if (!ValidationUtils.isValidName(studyName)) {
            errors.rejectValue("name", "StudyNameInvalid",
                "Invalid study name " + studyName);
        }
    }

    private void validateTable(TableModel table, Errors errors, SchemaValidationContext context) {
        String tableName = table.getName();
        List<ColumnModel> columns = table.getColumns();

        if (tableName != null && columns != null) {
            List<String> columnNames = columns.stream().map(ColumnModel::getName).collect(toList());
            if (ValidationUtils.hasDuplicates(columnNames)) {
                errors.rejectValue("schema", "DuplicateColumnNames");
            }
            context.addTable(tableName, columnNames);
        }
    }

    private void validateRelationshipTerm(RelationshipTermModel term, Errors errors, SchemaValidationContext context) {
        String table = term.getTable();
        String column = term.getColumn();
        if (table != null && column != null) {
            if (!context.isValidTableColumn(table, column)) {
                errors.rejectValue("schema", "InvalidRelationshipTermTableColumn",
                    "invalid table '" + table + "." + column + "'");
            }
        }
    }

    private void validateRelationship(RelationshipModel relationship, Errors errors, SchemaValidationContext context) {
        RelationshipTermModel fromTerm = relationship.getFrom();
        if (fromTerm != null) {
            validateRelationshipTerm(fromTerm, errors, context);
        }

        RelationshipTermModel toTerm = relationship.getTo();
        if (toTerm != null) {
            validateRelationshipTerm(toTerm, errors, context);
        }

        String relationshipName = relationship.getName();
        if (relationshipName != null) {
            context.addRelationship(relationshipName);
        }
    }

    private void validateAssetTable(
        AssetTableModel assetTable,
        Errors errors,
        SchemaValidationContext context) {

        String tableName = assetTable.getName();
        List<String> columnNames = assetTable.getColumns();
        if (tableName != null && columnNames != null) {
            // An empty list acts like a wildcard to include all columns from a table in the asset specification.
            if (columnNames.size() == 0) {
                if (!context.isValidTable(tableName)) {
                    errors.rejectValue("schema", "InvalidAssetTable",
                        "Invalid asset table: " + tableName);
                }
            } else {
                columnNames.forEach(
                    (columnName) -> {
                        if (!context.isValidTableColumn(tableName, columnName)) {
                            errors.rejectValue("schema", "InvalidAssetTableColumn",
                                "Invalid asset table: " + tableName + " column: " + columnName);
                        }
                    }
                );
            }
        }
    }

    private void validateAsset(AssetModel asset, Errors errors, SchemaValidationContext context) {
        List<AssetTableModel> assetTables = asset.getTables();

        if (assetTables != null) {
            boolean hasRootTable = false;
            for (AssetTableModel assetTable : assetTables) {
                validateAssetTable(assetTable, errors, context);
                if (assetTable.getName().equals(asset.getRootTable())) {
                    if (!context.isValidTableColumn(asset.getRootTable(), asset.getRootColumn())) {
                        errors.rejectValue("schema", "InvalidRootColumn",
                            "Invalid root table column. Table: " + asset.getRootTable() +
                                " Column: " + asset.getRootColumn());
                    }
                    hasRootTable = true;
                }
            }
            if (!hasRootTable) {
                errors.rejectValue("schema", "NoRootTable");
            }
        }

        List<String> follows = asset.getFollow();
        if (follows != null) {
            if (follows.stream().anyMatch(relationshipName -> !context.isValidRelationship(relationshipName))) {
                errors.rejectValue("schema", "InvalidFollowsRelationship");
            }
        }
        // TODO: There is another validation that can be done here to make sure that the graph is connected that has
        // been left out to avoid complexity before we know if we're going keep using this or not.
    }

    private void validateSchema(StudySpecificationModel schema, Errors errors) {
        SchemaValidationContext context = new SchemaValidationContext();
        List<TableModel> tables = schema.getTables();
        if (tables != null) {
            List<String> tableNames = tables.stream().map(TableModel::getName).collect(toList());
            if (ValidationUtils.hasDuplicates(tableNames)) {
                errors.rejectValue("schema", "DuplicateTableNames");
            }
            tables.forEach((table) -> validateTable(table, errors, context));
        }

        List<RelationshipModel> relationships = schema.getRelationships();
        if (relationships != null) {
            List<String> relationshipNames = relationships.stream().map(RelationshipModel::getName).collect(toList());
            if (ValidationUtils.hasDuplicates(relationshipNames)) {
                errors.rejectValue("schema", "DuplicateRelationshipNames");
            }
            relationships.forEach((relationship) -> validateRelationship(relationship, errors, context));
        }

        List<AssetModel> assets = schema.getAssets();
        if (assets != null) {
            List<String> assetNames = assets.stream().map(AssetModel::getName).collect(toList());
            if (ValidationUtils.hasDuplicates(assetNames)) {
                errors.rejectValue("schema", "DuplicateAssetNames");
            }
            if (assets.size() == 0) {
                errors.rejectValue("schema", "NoAssets");
            }
            assets.forEach((asset) -> validateAsset(asset, errors, context));
        }
    }

    @Override
    public void validate(@NotNull Object target, Errors errors) {
        if (target != null && target instanceof StudyRequestModel) {
            StudyRequestModel studyRequest = (StudyRequestModel) target;
            validateStudyName(studyRequest.getName(), errors);
            StudySpecificationModel schema = studyRequest.getSchema();
            if (schema != null) {
                validateSchema(schema, errors);
            }
        }
    }
}
