{{ with $environment := env "ENVIRONMENT" }}
{{ with $project := env "GOOGLE_CLOUD_PROJECT" }}
{{ with secret (printf "secret/dsde/datarepo/%s/proxy-sa.json $environment) }}

apiVersion: v1
kind: Secret
metadata:
  name: sql-proxy-sa
  namespace: data-repo
data:
  auth_provider_x509_cert_url: {{ .Data.auth_provider_x509_cert_url | base64Encode }}
  auth_uri: {{ .Data.auth_uri | base64Encode }}
  client_email: {{ .Data.client_email | base64Encode }}
  client_id: {{ .Data.client_id | base64Encode }}
  client_x509_cert_url: {{ .Data.client_x509_cert_url | base64Encode }}
  private_key: {{ .Data.private_key | base64Encode }}
  private_key_id: {{ .Data.private_key_id | base64Encode }}
  project_id: {{ .Data.project_id | base64Encode }}
  token_uri: {{ .Data.token_uri | base64Encode }}
  type: {{ .Data.type | base64Encode }}

{{end}}
{{end}}
{{end}}
