kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-pod-security-policy-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ["use"]
  resourceNames:
    - pod-running-policy 
