name: automerge
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  pull_request_review:
    types:
    - submitted
  check_suite:
    types:
    - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "broadinstitute/automerge-action@v0.8.5" # Forked from pascalgn/automerge-action
        env:
          GITHUB_TOKEN: "${{ secrets.DR_AUTOMERGE_TOKEN }}" # Intentionally merge as the GH actions user, which unlike Broadbot is not a repo admin
                                                      # This means status checks have to pass before the merge can occur.
          MERGE_METHOD: squash
          MERGE_FORKS: false
          MERGE_RETRIES: 24 # Retry for 2 minutes instead of 30s
