name: automerge
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  check_suite:
    types:
    - completed
  status: {}
jobs:
  automerge:
    # Only run action if PR includes "automerge" tag
    if: "contains( github.event.pull_request.labels.*.name, 'automerge')"
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "broadinstitute/automerge-action@v0.12.0" # Forked from pascalgn/automerge-action
        env:
          # merges even if checks have not passed & reviews not completed
          GITHUB_TOKEN: "${{ secrets.BROADBOT_TOKEN }}"
          # This step also checks for the automerge labbel
          MERGE_LABELS: "automerge"
          MERGE_METHOD: squash
          MERGE_FORKS: false
          MERGE_RETRIES: 24 # Retry for 2 minutes instead of 30s
