name: Update devs api image
on: pull_request
#on:
#  push:
#    branches:
#      - develop
jobs:
  devupdate:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Checkout datarepo-helm-definitions repo'
        uses: actions/checkout@v2
        with:
          repository: 'broadinstitute/datarepo-helm-definitions'
          token: ${{ secrets.HELM_REPO_TOKEN }}
          path: datarepo-helm-definitions
      - name: Install Yq
        uses: awesome-global-contributions/action-yq@v0.1.2
      - name: Get new image tag
        run: |
          TAG=$(git rev-parse --short HEAD)
          echo "::set-env name=TAG::${TAG}"
      - name: Find and replace image with current develop commit
        run: |
          which yq
          find . -name devDeployment.yaml -type f -print
          # find . -name devDeployment.yaml -type f -exec sh -c "yq w -i $1 'datarepo-api.image.version' ${TAG}" sh {} ';'
      #- name: Git add, commit and push
        #run: |
          # cd datarepo-helm-definitions
          # git add dev/dev/devDeployment.yaml
          # git commit -m "Updated dev image to latest jade-data-repo commit ${TAG}"
          # git push
