name: Integration test and Connected tests
env:
  GOOGLE_CLOUD_PROJECT: broad-jade-integration
  GOOGLE_REGION: us-central1
  K8_CLUSTER: integration-master
on:
  pull_request:
    branches:
      - develop
    paths:
      - '!*'
      - 'src/**'
      - 'gradle**'
      - 'gradle/**'
      - '**.gradle'
      - 'Dockerfile'
      - 'datarepo-clienttests/**'
      - '.github/workflows/int-and-connected-test-run.yml'
      - '.swagger-codegen-ignore'
  workflow_dispatch: {}
  schedule:
    - cron: '0 4 * * *' # run at 4 AM UTC, 12PM EST.
jobs:
  # test_connected:
  #   timeout-minutes: 180
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #   if: "!contains( github.event.pull_request.labels.*.name, 'skip-ci')"
  #   runs-on: ${{ matrix.os }}
  #   ## skips if pr label is 'skip-ci'
  #   # run a local Postgres container in Docker for the basic check tests
  #   services:
  #     postgres:
  #       image: postgres:11
  #       env:
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: postgres
  #         POSTGRES_DB: postgres
  #       ports:
  #         - 5432:5432
  #       options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  #   steps:
  #     - name: "Checkout code"
  #       uses: actions/checkout@v2
  #     - name: "Run Connected test via Gradle"
  #       uses: broadinstitute/datarepo-actions/actions/main@0.59.0
  #       with:
  #         actions_subcommand: 'gradleinttest'
  #         pgport: ${{ job.services.postgres.ports[5432] }}
  #         test_to_run: 'testConnected'
  #         role_id: ${{ secrets.ROLE_ID }}
  #         secret_id: ${{ secrets.SECRET_ID }}
  deploy_test_integration:
    timeout-minutes: 180
    strategy:
      matrix:
        os: [ubuntu-latest]
    if: "!contains( github.event.pull_request.labels.*.name, 'skip-ci')"
    runs-on: ${{ matrix.os }}
    ## skips if pr label is 'skip-ci'
    # run a local Postgres container in Docker for the basic check tests
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout jade-data-repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout datarepo-helm-definitions
        uses: actions/checkout@v2
        with:
          repository: "broadinstitute/datarepo-helm-definitions"
          token: ${{ secrets.BROADBOT_TOKEN }}
          path: datarepo-helm-definitions
      - name: Import Vault Secrets for Development GCR
        uses: hashicorp/vault-action@v2.1.2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.ROLE_ID }}
          secretId: ${{ secrets.SECRET_ID }}
          secrets: |
            secret/dsde/datarepo/dev/sa-key-b64 sa | B64_APPLICATION_CREDENTIALS ;
      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ env.GOOGLE_CLOUD_PROJECT }}
          service_account_key: ${{ env.B64_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
      - name: Configure Google Cloud SDK
        uses: broadinstitute/datarepo-actions/actions/configure-gcloud-sdk@0.49.0
      - name: Add Runner IP to allowlist
        uses: broadinstitute/datarepo-actions/actions/add-runner-ip@0.49.0
      - name: Lock namespace for use
        uses: broadinstitute/datarepo-actions/actions/lock-namespace@0.49.0
        env:
          K8_NAMESPACES: "integration-2"
      - name: Gradle build and upload Docker container
        uses: broadinstitute/gradle-command-action@v1
        with:
          arguments: jib
      - name: "Fetch gitHash for deployed integration version"
        id: configuration
        run: |
          git_hash=$(git rev-parse --short HEAD)
          echo "::set-output name=git_hash::$git_hash"
          echo "Latest git hash for this branch: $git_hash"
      - name: "[Deploy] Update int image tag to githash"
        uses: docker://mikefarah/yq:3.3.4
        with:
          args: yq w -i datarepo-helm-definitions/integration/${{ env.NAMESPACEINUSE }}/datarepo-api.yaml image.tag ${{ steps.configuration.outputs.git_hash }}
      - name: "[Deploy] Install Helmfile"
        uses: broadinstitute/setup-helmfile@v0.6.0 #Forked from mamezou-tech/setup-helmfile
      - name: "[Deploy] Use helmfile reapply helm for api pod to update version"
        run: |
          helmfile --version
          cd ${GITHUB_WORKSPACE}/${workingDir}/datarepo-helm-definitions/integration
          helmfile -e ${NAMESPACEINUSE} diff
          echo "Apply helm updates, including updated data-repo version"
          helmfile -e ${NAMESPACEINUSE} apply
          cd ${GITHUB_WORKSPACE}/${workingDir
      - name: "Wait for deployment to come back online"
        uses: broadinstitute/datarepo-actions/actions/wait-for-deployment@0.59.0
        timeout-minutes: 15
        env:
          DESIRED_GITHASH: ${{ steps.configuration.outputs.git_hash }}
          DEPLOYMENT_TYPE: 'api'
      # - name: "Run Test Runner smoke tests via Gradle"
      #   uses: broadinstitute/datarepo-actions/actions/main@0.59.0
      #   with:
      #     actions_subcommand: 'gradletestrunnersmoketest'
      # - name: "Run Integration test via Gradle"
      #   uses: broadinstitute/datarepo-actions/actions/main@0.59.0
      #   with:
      #     actions_subcommand: 'gradleinttest'
      #     pgport: ${{ job.services.postgres.ports[5432] }}
      #     test_to_run: 'testIntegration'
      - name: Unlock namespace for use
        if: always()
        uses: broadinstitute/datarepo-actions/actions/unlock-namespace@0.49.0
      - name: Remove Runner IP from allowlist
        if: always()
        uses: broadinstitute/datarepo-actions/actions/rm-runner-ip@0.49.0
      # - name: "Notify Jade Slack on nightly test run"
      #   if: ${{ github.event_name == 'schedule' && always() }}
      #   uses: broadinstitute/action-slack@v3.8.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   with:
      #     status: ${{ job.status }}
      #     channel: "#jade-alerts"
      #     username: "Data Repo tests"
      #     text: "Integration and Connected tests"
