name: Alpha Nightly
on:
  pull_request:
    branches:
      - develop

#  schedule:
#    - cron: '0 2 * * *' # run at 2 AM UTC
#branches:
#  - develop

jobs:
  update_image:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Checkout tag for DataBiosphere/jade-data-repo'
        run: |
          git checkout ${{ steps.previoustag.outputs.tag }}
      - name: 'Checkout DataBiosphere/jade-data-repo-ui repo'
        uses: actions/checkout@v2
        with:
          repository: 'DataBiosphere/jade-data-repo-ui'
          token: ${{ secrets.HELM_REPO_TOKEN }}
          path: jade-data-repo-ui
