# Note that this action is called from the UI build process:
# https://github.com/DataBiosphere/jade-data-repo-ui/blob/develop/.github/workflows/build.yaml#L41
# Changes merged here require a version bump in that action.
name: Tag
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: "The branch, tag or SHA to checkout"
        default: ''
        required: false
        type: string
      dry-run:
        description: "Determine the next version without tagging the branch. The workflow can use the outputs new_tag and tag in subsequent steps. Possible values are true and false (default)"
        default: false
        required: false
        type: string
      print-tag:
        description: "Echo tag to console"
        default: true
        required: false
        type: string
      release-branches:
        description: "Default branch (main, develop, etc)"
        default: 'main'
        required: false
        type: string
      version-file-path:
        description: "If present, update the version number in that file"
        default: build.gradle
        required: false
        type: string
      version-line-match:
        description: "If present, a grep regular expression to identify the line containing the version number in the VERSION_FILE_PATH."
        default: "^\\s*version\\s\\+'.*'"
        required: false
        type: string
      version-suffix:
        description: "Suffix added to the version in the version file, such as, -SNAPSHOT."
        default: SNAPSHOT
        required: false
        type: string
    outputs:
      tag:
        description: "The value of the latest tag after running this action"
        value: ${{ jobs.tag-job.outputs.tag }}
      new-tag:
        description: "The value of the newly created tag"
        value: ${{ jobs.tag-job.outputs.new-tag }}
    secrets:
      BROADBOT_TOKEN:
        required: true

jobs:
  # On tag vs. new-tag.
  # The new-tag is always the tag resulting from a bump to the original tag.
  # However, the tag is by definition the value of the latest tag after running the action,
  # which might not change if dry run is used, and remains same as the original tag.
  tag-job:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      new-tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: Checkout current code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.BROADBOT_TOKEN }} # this allows the push to succeed later
          persist-credentials: false
      - name: Bump the tag to a new version
        # https://github.com/DataBiosphere/github-actions/tree/master/actions/bumper
        uses: databiosphere/github-actions/actions/bumper@bumper-0.3.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
          HOTFIX_BRANCHES: hotfix.*
          DEFAULT_BUMP: minor
          DRY_RUN: ${{ inputs.dry-run }}
          RELEASE_BRANCHES: ${{ inputs.release-branches }}
          VERSION_FILE_PATH: ${{ inputs.version-file-path }}
          VERSION_LINE_MATCH: ${{ inputs.version-line-match }}
          VERSION_SUFFIX: ${{ inputs.version-suffix }}
      - name: Echo tag to console
        if: ${{ inputs.print-tag == 'true' }}
        run: |
          echo "Newly created version tag: '${NEW_TAG}'"
          echo "${{ inputs.version-file-path }}"
          echo "==============="
          cat ${{ inputs.version-file-path }}
        env:
          NEW_TAG: ${{ steps.tag.outputs.new_tag }}
