name: Track semVer though environments

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  schedule:
    - cron: '0 */3 * * *' # run every 3 hours and on push
jobs:
  get_versions:
    name: Get semVer for environments
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          endPoints+=( "https://jade.datarepo-dev.broadinstitute.org/configuration" \
            "https://data.alpha.envs-terra.bio/configuration" \
            "https://data.staging.envs-terra.bio/configuration" \
            "https://data.terra.bio/configuration")

          for i in ${endPoints[@]}; do
            if [[ "$i" == *"dev"* ]]
            then
             env=dev
            elif [[ "$i" == *"alpha"* ]]
            then
             env=alpha
            elif [[ "$i" == *"staging"* ]]
            then
             env=staging
            elif [[ "$i" == *"data.terra.bio"* ]]
            then
             env=production
            else
             echo "No env found"
            fi
            date=$(date +%Y-%m-%d\ %H:%M:%S)
            semVer=$(curl -s $i | jq -r '.semVer')
            cat <<< $(jq --arg env "$env" \
              --arg date "$date" \
              --arg semVer "$semVer" \
              '.data += [{"env": "'"$env"'", "date": "'"$date"'", "semVer": "'"$semVer"'"}]' endpoints.json) \
              > endpoints.json
          done
      - name: Upload result for environments
        uses: actions/upload-artifact@v2
        with:
          name: teack deploys
          path: endpoints.json
